#pragma once

const unsigned int	g_iBackCX = 1280;
const unsigned int	g_iBackCY = 768;

enum SCENEID {SCENE_STATIC, SCENE_LOGO, SCENE_MENU,SCENE_STAGE, SCENE_HOUSE, SCENE_FARM, SCENE_TOWN, SCENE_SHOP, SCENE_ROAD, SCENE_CAVE, SCENE_END};
